version: "3"

services:
    server:
        build: .
        command: ./server
        ports:
            - "8000:8000"
        depends_on:
            - mongo
        volumes:
            - ./upload:/upload
    
    mongo:
        image: "mongo:4.2.3"
        ports:
            - "27017:27017"
        volumes:
            - ./init:/docker-entrypoint-initdb.d
